### ISSUE TITLE
UI 문의드립니다!

### ISSUE THREAD

**Issue by zjacom** [wisdomstar94/tistory-discord-ui-skin#1]
안녕하세요, 디스코드 UI 블로그 스킨을 사용하고 있는 사람입니다!

먼저 이렇게 멋진 스킨을 제작해주셔서 감사합니다.

한 가지 문의 사항이 있습니다!

한 페이지에 존재하는 모든 글을 다 읽었을 때, 다음 페이지로 넘어가는 버튼이 중앙에 있었으면 좋겠습니다.
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/cd780a1a-b07d-4df6-9975-770be55ac584">

이거는 제 개인적인 바람이기 때문에 수정하시지 않아도 상관 없습니다!

다시 한 번 멋진 스킨을 제작해주셔서 감사의 말씀 전해드립니다!

**Comment by wisdomstar94** [comment]
안녕하세요. 이슈 남겨주셔서 감사합니다.

다음과 같이 페이지네이션 부분에 대한 수평 정렬을 조정할 수 있는 스킨 옵션을 추가했습니다.
![image](https://github.com/user-attachments/assets/da2eb6ef-597c-4ed0-b448-d3da4b019c3b)

[최신 버전](https://github.com/wisdomstar94/tistory-discord-ui-skin/releases/latest)에서 확인 가능하니 확인 후 원하시던 기능이 맞으시다면 본 이슈를 닫아주시면 감사하겠습니다!

**Comment by zjacom** [comment]
감사합니다.

근데 변경 사항이 생기면서 새로운 문제가 생겼습니다.
<img width="1512" alt="스크린샷 2024-10-15 오후 12 18 23" src="https://github.com/user-attachments/assets/402518de-c36f-40fb-a3ed-8462cf51b814">

위와 같이 블로그를 먼저 들어가지 않고, 스킨 편집을 먼저 들어가는 경우 (예, 아니오) 버튼을 아예 클릭할 수 없습니다.
그래서 저 같은 경우에는 새로 ZIP 파일을 다운로드 받아 업데이트를 진행했습니다.

그리고 이건 별개의 말씀인데, 본문 텍스트 사이의 줄 간격을 설정할 수 있을까요?
개인적으로 좁다고 느껴져서 조금 늘리고 싶습니다.

**Comment by wisdomstar94** [comment]
안녕하세요.

스킨 미리보기 화면에서는 업데이트 체크가 이루어지지 않도록 수정하였고,
본문 글 텍스트 줄 간격을 설정할 수 있는 스킨 옵션을 추가했습니다.
![image](https://github.com/user-attachments/assets/b4875678-874e-41fe-b34d-61739cca6b6a)

[최신버전](https://github.com/wisdomstar94/tistory-discord-ui-skin/releases/latest)으로 스킨 교체 후 확인 부탁드리겠습니다~

**Comment by zjacom** [comment]
본문 글 텍스트 줄 간격은 잘되는데, 스킨 미리보기 화면에서는 아직도 업데이트 체크가 이루어지고 있습니다.

**Comment by wisdomstar94** [comment]
스킨 미리보기 화면이라고 하시는 부분에 대한 url 이 `/manage/design/skin/edit` 맞으실까요?

맞다면, 제가 테스트 해볼 때는 iframe 에서 로드 된 걸 잘 인식하긴 하더라구요 (아래 이미지 처럼 alert 로 테스트해보니 스킨미리보기에서 해당 if 문을 타는 것을 확인) 
![image](https://github.com/user-attachments/assets/f3416c78-98b1-4e6f-ab81-fb4f7d52ddaa)

해당 if 문을 탔다면 업데이트 체크가 이루어지지 않아야 정상인데, 
왜 제 스킨편집 화면에선 잘 되고 zjacom 님 화면에선 안되는 것일까요.. 흠..

혹시 브라우저는 크롬 쓰고 계신게 맞으실까요?

**Comment by zjacom** [comment]
네 맞습니다..
조금 더 확실한 상황은 스킨 편집을 누르면 나오는 스킨 미리보기 화면입니다.

**Comment by wisdomstar94** [comment]
@zjacom 
다시 테스트 해봐도 저는 미리보기 화면에선 업데이트 체크가 안일어나고 있네요..
현재 이 글을 작성하는 기준으로 최신 버전이 v0.0.15 인데, v0.0.15 버전으로 적용하신 후 이후에 새로운 버전이 나왔을 때도
동일한 현상이 발생되시면 그 때 다시 말씀 부탁드리겠습니다!

**Comment by zjacom** [comment]
네 알겠습니다!
