### ISSUE TITLE
본문 줄 간격

### ISSUE THREAD

**Issue by zjacom** [wisdomstar94/tistory-discord-ui-skin#2]
안녕하세요! 저번에도 issue 열었던 사람입니다.

저번에는 본문 줄 간격에 대한 issue를 열었었는데, 막상 줄 간격을 늘리고 보니 코드의 줄 간격 또한 비약적으로 증가하게 되었습니다...

코드 박스의 줄간격도 따로 설정할 수 있을까요?

**Comment by wisdomstar94** [comment]
안녕하세요. 

스킨 옵션에 코드블럭에 대한 줄 간격 설정도 추가하여 [v0.0.16](https://github.com/wisdomstar94/tistory-discord-ui-skin/releases/tag/v0.0.16) 으로 배포하였습니다.
![image](https://github.com/user-attachments/assets/6d813442-cc4d-44fd-a535-70b9c5fb85fa)

[최신 버전](https://github.com/wisdomstar94/tistory-discord-ui-skin/releases/latest)으로 스킨 교체 후 확인해보실 수 있으실 겁니다. :)

**Comment by zjacom** [comment]
감사합니다!
